server:
  address: localhost
  port: 8083

spring:
  application.name: carinfo-service
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudchain?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true

feign:
  hystrix.enabled: true
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000


logging:
  level:
    org.hibernate: DEBUG
